name: stocks
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  auto_route: ^7.9.0
  auto_route_generator: ^7.3.2
  bloc: ^8.1.3
  build_runner: ^2.4.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  flutter_native_splash: ^2.3.10
  flutter_screenutil: ^5.9.0
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.0
  firebase_remote_config: ^4.3.17
  overlay_support: ^2.1.0
  flutter_inappwebview: ^6.0.0
  awesome_dialog: ^3.2.0
  get: ^4.6.6
  after_layout: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/stocks/
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins/Poppins-Regular.ttf
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: fonts/Poppins/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: fonts/Poppins/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-ThinItalic.ttf
          weight: 100
          style: italic

flutter_native_splash:
  color: "#2D0E46"
  image: assets/images/logo.png
